name: CI

on: [push]

jobs:
  jekyll_build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🧪 Build and deploy
        uses: victoriadrake/jekyll-cd@master
      - name: 📦Sync S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_KEY }}
          SOURCE_DIR: 'docs'      # optional: defaults to entire repository
          AWS_S3_ENDPOINT: ${{ secrets.ENDPOINT }}
